# Generated by Django 4.2.7 on 2025-05-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenoneseven', '0013_alter_detallecompras_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
