# Generated by Django 4.2.7 on 2025-05-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenoneseven', '0014_usuario_token_verificacion_usuario_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='TokenClave',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
